groups:
  - name: react-app-alerts
    rules:
      - alert: ReactAppDown
        expr: probe_success{job="react-app-probe"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "React App is down"
          description: "Target {{ $labels.instance }} is down"
